### ISSUE TITLE
Issue when analyzing behaviors. 

### ISSUE THREAD

**Issue by GKNM995** [umyelab/LabGym#234]
Hi, 

I trained a categorizer that seems to work well but gives an error (shown below) for some of the videos and won't analyze them. Any idea how this can be fixed?
![image](https://github.com/user-attachments/assets/54165875-3e17-42fc-9baf-e3b0e5a9b1d3)

I am using LabGym version 2.7.1 in WSL (Windows 10). 

Thank you for your help!

**Comment by yujiahu415** [comment]
Hi,

You mixed the function of Categorizer with Detector. The Detector is used to detect animals or objects, not behaviors. The Categorizer is used to categorize behaviors. You labeled behaviors like 'grooming' to train a Detector so it considered these behaviors as 'animal/object kind'. So when a behavior you labeled (which was considered as 'an animal kind') didn't show up at any frame in a video, you got this error.

You should instead label animals like 'mouse' to train a Detector, and use the trained Detector to generate behavior examples and sort them into different behavior categories and then train a Categorizer on the sorted behavior examples. Finally, use the trained Detector and Categorizer to analyze videos.

**Comment by GKNM995** [comment]
Hello again,

I get this error when I attempt to sort behavior examples using the GUI:
Traceback (most recent call last):
  File "/home/gabie/.local/lib/python3.10/site-packages/LabGym/gui_categorizer.py", line 814, in sort_behaviors
    pattern_images=sorted(pattern_images,key=lambda name:int(name.split('_len')[0].split('_')[-1]))
  File "/home/gabie/.local/lib/python3.10/site-packages/LabGym/gui_categorizer.py", line 814, in <lambda>
    pattern_images=sorted(pattern_images,key=lambda name:int(name.split('_len')[0].split('_')[-1]))
ValueError: invalid literal for int() with base 10: 'high.jpg'

Any idea how I can fix this? Thank you!

**Comment by yujiahu415** [comment]
Hi,
How did you sort the behavior examples? Looks like you didn't use the behavior examples generated by LabGym for the sorting? The behavior examples generated by LabGym has its unique name format so that the 'sort behavior examples' UI can read the name correctly.
Can you screenshot the steps of how you generated the behavior examples and sorted them? Can you also screenshot the names of the files you want to sort?

**Comment by GKNM995** [comment]
Hi,

Here's a screenshot for behavior example generation parameters:
![Generate_behavior_examples_parameters](https://github.com/user-attachments/assets/1d07d71b-c0c4-48e4-a7fc-50ce40570ab4)

Here are the contents of the behavior examples folder:
![Contents of behavior examples folder](https://github.com/user-attachments/assets/e86d2bd1-b976-4209-ae8b-2a6314c199ef)

Here's the path to the actual examples shown below: 
![Behavior example path](https://github.com/user-attachments/assets/8654f852-c4a1-4eda-aed4-d8e21d6aa2cc)

Here are the examples generated:
![Behavior examples generated](https://github.com/user-attachments/assets/bc9f5570-72f1-4eeb-9e24-a084e8423eb6)

Here are the "sort behavior" parameters I used:
![Sort behavior examples settings](https://github.com/user-attachments/assets/ce18b676-d3d6-4edb-adbb-03529a10c71c)

Here's the error I am currently dealing with:
![sort_error](https://github.com/user-attachments/assets/2caea466-e9d2-4d80-92c9-8993f3210316)

Thank you for your help!

**Comment by yujiahu415** [comment]
Hi,
All is good except that the directory to unsorted examples should be '...\Mouse_0\' rather than your current '...\Behavior_examples \'. That means you need to go two levels of subfolder further when selecting the folder that stores the unsorted behavior examples.
By the way, I also noticed that the fps of your video is 60, which is unnecessary high for rodent behaviors. You can use the preprocessing module in LabGym to reduce the fps to 15, which can triple your analysis speed without losing accuracy. But note that if you reduce fps, you need to do the same thing for all your videos. A Categorizer trained on 15-fps video would not work well for 60-fps videos. And you also need to adjust the length of one behavior example from the current 15-frame to, for example, 10 frames or even 8 frames.

**Comment by GKNM995** [comment]
Thank you for the quick response and the great advice. Changing the directory worked!

**Comment by yujiahu415** [comment]
Oh I also noticed that you included body parts and set 'std' to 0, which may include too many unnecessary details in the pattern images. Are your videos side/front view or top view? If they're side/front view you can include body parts with std=50; if they're top view, you typically don't need to include body parts in pattern images.
